---
application:
  name: "qovery-nodejs"
  project: "qovery-nodejs"
  organization: "QoveryCommunity"
  publicly_accessible: true
  port: 5000
databases:
- type: "MONGODB"
  name: "qovery"
  version: "4.4"
routers:
- name: "main-qovery-nodejs"
  routes:
  - application_name: "qovery-nodejs"
    paths:
    - "/*"
